"""
Streamlit Dashboard for CRM Sales Forecast Pipeline
Displays forecast results, charts, and performance metrics
"""

import sys
import os

# --- Auto-detect venv Python and re-launch if needed ---
_VENV_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "venv")
_VENV_PYTHON = os.path.join(_VENV_DIR, "Scripts", "python.exe") if os.name == "nt" else os.path.join(_VENV_DIR, "bin", "python")
if os.path.isfile(_VENV_PYTHON) and os.path.abspath(sys.executable) != os.path.abspath(_VENV_PYTHON):
    os.execv(_VENV_PYTHON, [_VENV_PYTHON] + sys.argv)

# --- Fix Windows console encoding for Unicode characters ---
if sys.stdout and hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
if sys.stderr and hasattr(sys.stderr, 'reconfigure'):
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import os

# Set page configuration
st.set_page_config(
    page_title="CRM Sales Forecast Dashboard",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom styling
st.markdown("""
    <style>
    .metric-box {
        background-color: #f0f2f6;
        padding: 20px;
        border-radius: 10px;
        margin: 10px 0;
    }
    .title-box {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        padding: 20px;
        border-radius: 10px;
        margin-bottom: 20px;
    }
    </style>
""", unsafe_allow_html=True)

# Title
st.markdown("""
    <div class="title-box">
        <h1>🎯 CRM Sales Forecast Dashboard</h1>
        <p>Optimized Prophet Model with Mistral AI Integration</p>
    </div>
""", unsafe_allow_html=True)

# Sidebar Configuration
st.sidebar.header("📋 Dashboard Controls")
show_data = st.sidebar.checkbox("Show Raw Data", value=True)
show_historical = st.sidebar.checkbox("Show Historical Performance", value=True)
show_forecast = st.sidebar.checkbox("Show Future Forecast", value=True)

# ============================================================
# LOAD DATA
# ============================================================

def load_data():
    """Load CSV files generated by forecast_backup.py"""
    data = {}
    
    try:
        # Load forecast results
        if os.path.exists("prophet_sales_forecast_results.csv"):
            data['forecast'] = pd.read_csv("prophet_sales_forecast_results.csv")
        
        # Load historical performance
        if os.path.exists("prophet_historical_performance.csv"):
            data['historical'] = pd.read_csv("prophet_historical_performance.csv")
        
        # Load synthetic data
        if os.path.exists("territory_single_prophet_ready.csv"):
            data['synthetic'] = pd.read_csv("territory_single_prophet_ready.csv")
    
    except Exception as e:
        st.error(f"Error loading data: {e}")
    
    return data

data = load_data()

# ============================================================
# KEY METRICS
# ============================================================

st.sidebar.markdown("---")
st.sidebar.header("🎯 Key Metrics")

if 'historical' in data:
    hist_df = data['historical']
    
    # Calculate metrics
    rmse = np.sqrt(np.mean(hist_df['Error']**2))
    mean_sales = hist_df['Actual_Sales'].mean()
    rmse_pct = (rmse / mean_sales * 100) if mean_sales != 0 else 0
    mape = hist_df['Percentage_Error'].abs().mean()
    mae = hist_df['Absolute_Error'].mean()
    
    col1, col2 = st.sidebar.columns(2)
    with col1:
        st.metric("RMSE %", f"{rmse_pct:.2f}%", delta="Excellent" if rmse_pct < 5 else "Good")
    with col2:
        st.metric("MAPE", f"{mape:.2f}%")
    
    col3, col4 = st.sidebar.columns(2)
    with col3:
        st.metric("MAE", f"${mae:,.0f}")
    with col4:
        st.metric("Mean Sales", f"${mean_sales:,.0f}")

# ============================================================
# MAIN DASHBOARD TABS
# ============================================================

tab1, tab2, tab3, tab4, tab5 = st.tabs(["📊 Overview", "📈 Forecast", "📉 Historical", "📋 Data", "⚙️ Settings"])

# ============================================================
# TAB 1: OVERVIEW
# ============================================================

with tab1:
    st.header("📊 Forecast Overview")
    
    col1, col2, col3, col4 = st.columns(4)
    
    if 'historical' in data:
        hist_df = data['historical']
        rmse = np.sqrt(np.mean(hist_df['Error']**2))
        mean_sales = hist_df['Actual_Sales'].mean()
        rmse_pct = (rmse / mean_sales * 100) if mean_sales != 0 else 0
        mape = hist_df['Percentage_Error'].abs().mean()
        mae = hist_df['Absolute_Error'].mean()
        
        with col1:
            st.metric("RMSE (% of Mean)", f"{rmse_pct:.2f}%", "✅ Excellent" if rmse_pct < 5 else "⚠️ Good")
        with col2:
            st.metric("MAPE", f"{mape:.2f}%", "Accuracy")
        with col3:
            st.metric("MAE", f"${mae:,.0f}", "Avg Error")
        with col4:
            st.metric("Data Points", f"{len(hist_df)}", "Historical")
    
    st.markdown("---")
    
    # Performance Summary
    if 'historical' in data:
        st.subheader("📊 Model Performance Summary")
        col1, col2 = st.columns(2)
        
        with col1:
            st.info(f"""
            ### ✅ Model Status: EXCELLENT
            - **RMSE**: {rmse_pct:.2f}% of mean sales
            - **Interpretation**: 🎯 Ideal for CRM forecasting & target-setting
            - **Recommendation**: Ready for production deployment
            """)
        
        with col2:
            st.success(f"""
            ### 🚀 Performance Metrics
            - **Training Data**: 44 months
            - **Holdout Test**: 3 months  
            - **Forecast Horizon**: 12 months
            - **Feature Count**: 9 regressors
            - **Grid Search**: 22 parameter combinations
            """)

# ============================================================
# TAB 2: FORECAST
# ============================================================

with tab2:
    st.header("📈 Future Sales Forecast (12 Months)")
    
    if 'forecast' in data:
        forecast_df = data['forecast'].copy()
        
        # Display forecast table
        if st.checkbox("Show Forecast Data Table"):
            st.dataframe(forecast_df, use_container_width=True)
        
        # Forecast visualization
        st.subheader("📊 Forecast Chart")
        
        fig, ax = plt.subplots(figsize=(12, 6))
        
        # Convert Month to datetime for plotting
        forecast_df['Month'] = pd.to_datetime(forecast_df['Month'])
        
        ax.plot(forecast_df['Month'], forecast_df['Forecast_Sales'], 
                marker='o', linewidth=2, label='Forecast Sales', color='#667eea')
        ax.plot(forecast_df['Month'], forecast_df['Target_Sales'], 
                marker='s', linewidth=2, label='Target Sales', color='#764ba2')
        ax.fill_between(forecast_df['Month'], 
                         forecast_df['Lower_Bound'], 
                         forecast_df['Upper_Bound'],
                         alpha=0.2, color='#667eea', label='70% Confidence Band')
        
        ax.set_xlabel('Month', fontsize=12)
        ax.set_ylabel('Sales ($)', fontsize=12)
        ax.set_title('12-Month Sales Forecast with Target Rule', fontsize=14, fontweight='bold')
        ax.legend(loc='best')
        ax.grid(True, alpha=0.3)
        plt.xticks(rotation=45)
        plt.tight_layout()
        
        st.pyplot(fig)
        
        # Forecast statistics
        st.subheader("📊 Forecast Statistics")
        col1, col2, col3, col4 = st.columns(4)
        
        with col1:
            st.metric("Avg Forecast", f"${forecast_df['Forecast_Sales'].mean():,.0f}")
        with col2:
            st.metric("Avg Target", f"${forecast_df['Target_Sales'].mean():,.0f}")
        with col3:
            st.metric("Min Forecast", f"${forecast_df['Forecast_Sales'].min():,.0f}")
        with col4:
            st.metric("Max Forecast", f"${forecast_df['Forecast_Sales'].max():,.0f}")
        
        # Regressor values
        st.subheader("🔧 Future Regressor Values")
        regressors = [col for col in forecast_df.columns if col not in 
                     ['Month', 'Forecast_Sales', 'Target_Sales', 'Lower_Bound', 'Upper_Bound']]
        
        if regressors:
            selected_regressor = st.selectbox("Select Regressor to Visualize", regressors)
            
            if selected_regressor:
                fig, ax = plt.subplots(figsize=(12, 5))
                ax.plot(forecast_df['Month'], forecast_df[selected_regressor], 
                       marker='o', linewidth=2, color='#667eea')
                ax.set_xlabel('Month', fontsize=11)
                ax.set_ylabel(selected_regressor, fontsize=11)
                ax.set_title(f"{selected_regressor} Projection", fontsize=13, fontweight='bold')
                ax.grid(True, alpha=0.3)
                plt.xticks(rotation=45)
                plt.tight_layout()
                st.pyplot(fig)

# ============================================================
# TAB 3: HISTORICAL PERFORMANCE
# ============================================================

with tab3:
    st.header("📉 Historical Performance Analysis")
    
    if 'historical' in data:
        hist_df = data['historical'].copy()
        
        # Performance table
        if st.checkbox("Show Historical Data Table", value=True):
            st.dataframe(hist_df, use_container_width=True)
        
        # Actual vs Predicted
        st.subheader("📊 Actual vs Predicted Sales")
        
        fig, ax = plt.subplots(figsize=(14, 6))
        
        months = range(len(hist_df))
        ax.plot(months, hist_df['Actual_Sales'], marker='o', label='Actual Sales', 
               linewidth=2, color='#2ecc71', markersize=5)
        ax.plot(months, hist_df['Predicted_Sales'], marker='s', label='Predicted Sales', 
               linewidth=2, color='#e74c3c', markersize=4)
        
        ax.fill_between(months, hist_df['Actual_Sales'], hist_df['Predicted_Sales'],
                        alpha=0.2, color='gray')
        
        ax.set_xlabel('Month Index', fontsize=12)
        ax.set_ylabel('Sales ($)', fontsize=12)
        ax.set_title('Historical: Actual vs Predicted Sales', fontsize=14, fontweight='bold')
        ax.legend(loc='best', fontsize=10)
        ax.grid(True, alpha=0.3)
        plt.tight_layout()
        
        st.pyplot(fig)
        
        # Residuals Analysis
        st.subheader("📊 Residuals Analysis")
        
        fig, axes = plt.subplots(1, 2, figsize=(14, 5))
        
        # Residuals over time
        axes[0].plot(months, hist_df['Error'], marker='o', color='#f39c12', linewidth=2)
        axes[0].axhline(y=0, color='red', linestyle='--', linewidth=1)
        axes[0].fill_between(months, hist_df['Error'], 0, alpha=0.3, color='#f39c12')
        axes[0].set_xlabel('Month Index', fontsize=11)
        axes[0].set_ylabel('Error ($)', fontsize=11)
        axes[0].set_title('Residuals Over Time', fontsize=12, fontweight='bold')
        axes[0].grid(True, alpha=0.3)
        
        # Error distribution
        axes[1].hist(hist_df['Error'], bins=15, color='#3498db', alpha=0.7, edgecolor='black')
        axes[1].axvline(x=hist_df['Error'].mean(), color='red', linestyle='--', 
                       linewidth=2, label=f"Mean: ${hist_df['Error'].mean():,.0f}")
        axes[1].set_xlabel('Error ($)', fontsize=11)
        axes[1].set_ylabel('Frequency', fontsize=11)
        axes[1].set_title('Error Distribution', fontsize=12, fontweight='bold')
        axes[1].legend()
        axes[1].grid(True, alpha=0.3, axis='y')
        
        plt.tight_layout()
        st.pyplot(fig)
        
        # Performance metrics
        st.subheader("📊 Detailed Metrics")
        
        col1, col2, col3, col4, col5 = st.columns(5)
        
        with col1:
            st.metric("Mean Error", f"${hist_df['Error'].mean():,.0f}")
        with col2:
            st.metric("Std Dev Error", f"${hist_df['Error'].std():,.0f}")
        with col3:
            st.metric("Min Error", f"${hist_df['Error'].min():,.0f}")
        with col4:
            st.metric("Max Error", f"${hist_df['Error'].max():,.0f}")
        with col5:
            st.metric("R² Score", f"{(1 - np.var(hist_df['Error']) / np.var(hist_df['Actual_Sales'])):.4f}")

# ============================================================
# TAB 4: DATA EXPLORER
# ============================================================

with tab4:
    st.header("📋 Data Explorer")
    
    # Select dataset
    dataset_option = st.selectbox("Select Dataset", 
                                  ["Forecast Results", "Historical Performance", "Synthetic Data"])
    
    if dataset_option == "Forecast Results" and 'forecast' in data:
        st.subheader("📊 Forecast Results")
        st.dataframe(data['forecast'], use_container_width=True)
        
        # Download button
        csv = data['forecast'].to_csv(index=False)
        st.download_button("Download Forecast CSV", csv, 
                          "forecast_results.csv", "text/csv")
    
    elif dataset_option == "Historical Performance" and 'historical' in data:
        st.subheader("📉 Historical Performance")
        st.dataframe(data['historical'], use_container_width=True)
        
        # Download button
        csv = data['historical'].to_csv(index=False)
        st.download_button("Download Historical CSV", csv, 
                          "historical_performance.csv", "text/csv")
    
    elif dataset_option == "Synthetic Data" and 'synthetic' in data:
        st.subheader("🔧 Synthetic Data")
        st.dataframe(data['synthetic'], use_container_width=True)
        
        # Download button
        csv = data['synthetic'].to_csv(index=False)
        st.download_button("Download Synthetic Data CSV", csv, 
                          "synthetic_data.csv", "text/csv")

# ============================================================
# TAB 5: SETTINGS & INFO
# ============================================================

with tab5:
    st.header("⚙️ Settings & Information")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("📋 Model Configuration")
        st.info("""
        **Forecast Model**: Prophet (Bayesian Time-Series)
        
        **Data Settings**:
        - Synthetic Data: 47 months (2022-01 to 2025-11)
        - Train/Test Split: 44/3 months
        - Forecast Horizon: 12 months
        
        **Feature Engineering**:
        - Lag features (lag1, lag2)
        - Rolling averages (3-month window)
        - Interaction terms
        - Total regressors: 9
        
        **Hyperparameter Optimization**:
        - Grid search: 22 parameter combinations
        - Selection criterion: CV RMSE (log scale)
        - Best model CV RMSE: 1.4179
        """)
    
    with col2:
        st.subheader("🎯 Performance Summary")
        st.success("""
        **Model Performance**:
        - Holdout RMSE: 1.15% of mean
        - MAPE: 0.97%
        - Status: 🎯 Excellent
        
        **Interpretation**:
        Ideal for CRM forecasting & 
        target-setting. Ready for 
        production deployment.
        
        **Target Rule**:
        - Strategy: Function-based uplift
        - Formula: 1.05 + 0.40×close_rate + 0.25×territory_potential
        - Clip range: 1.08 - 1.35
        """)
    
    st.markdown("---")
    
    st.subheader("📁 Generated Files")
    
    files_info = {
        "prophet_sales_forecast_results.csv": "12-month forecast with targets",
        "prophet_historical_performance.csv": "47-month historical performance",
        "territory_single_prophet_ready.csv": "Synthetic training data",
        "prophet_optimized_forecast.png": "Forecast visualization",
    }
    
    for filename, description in files_info.items():
        if os.path.exists(filename):
            file_size = os.path.getsize(filename) / 1024  # KB
            st.success(f"✅ {filename} ({file_size:.1f} KB) - {description}")
        else:
            st.warning(f"⚠️ {filename} - Not found")
    
    st.markdown("---")
    
    st.subheader("🔗 Resources")
    col1, col2, col3 = st.columns(3)
    
    with col1:
        st.markdown("[📚 Prophet Documentation](https://facebook.github.io/prophet/)")
    with col2:
        st.markdown("[🤖 Mistral AI](https://mistral.ai/)")
    with col3:
        st.markdown("[💻 GitHub Repository](https://github.com/hafsa1meshhen-cell/SalesForcasting)")
    
    st.markdown("---")
    st.caption("CRM Sales Forecast Dashboard | Powered by Streamlit & Prophet | December 2025")


# ============================================================
# FOOTER
# ============================================================

st.markdown("---")
st.markdown("""
<div style='text-align: center'>
    <p style='color: #888; font-size: 12px;'>
        Dashboard automatically updates when forecast_backup.py generates new data<br>
        Last Updated: """ + datetime.now().strftime("%Y-%m-%d %H:%M:%S") + """
    </p>
</div>
""", unsafe_allow_html=True)
